create schema practica_videoclub;

set schema 'practica_videoclub';

create table socio(
	id smallserial primary key,
	nombre varchar(40) not null,
	apellido varchar(80) not null,
	identificacion varchar(10) not null,
	fecha_nacimiento date not null
);

create table genero(
	id smallserial primary key,
	valor varchar(40) not null
);

create table pelicula(
	id smallserial primary key,
	titulo varchar(80) not null,
	id_genero smallint not null,
	id_director smallint not null,
	sinopsis text not null
);

create table copia(
	id smallserial primary key,
	valor smallint not null,
	id_pelicula smallint not null
);

create table direccion(
	id smallserial primary key,
	calle varchar(80) not null,
	numero varchar(5) not null,
	piso varchar(10) not null,
	cp integer not null
);

create table director(
	id smallserial primary key,
	nombre varchar(90) not null
);

create table telefono(
	id smallserial primary key,
	valor varchar(15) not null,
	id_socio smallint not null
);

create table prestamo(
	id smallserial primary key,
	id_socio smallint not null,
	id_copia smallint not null,
	fecha_retiro date not null,
	fecha_devolucion date
);

CREATE TABLE tmp_videoclub (
	id_copia int4 NULL,
	fecha_alquiler_texto date NULL,
	dni varchar(50) NULL,
	nombre varchar(50) NULL,
	apellido_1 varchar(50) NULL,
	apellido_2 varchar(50) NULL,
	email varchar(50) NULL,
	telefono varchar(50) NULL,
	codigo_postal varchar(5) NULL,
	fecha_nacimiento varchar(50) NULL,
	numero varchar(5) NULL,
	piso varchar(5) NULL,
	letra varchar NULL,
	calle varchar NULL,
	ext varchar(50) NULL,
	titulo varchar(80) NULL,
	genero varchar(50) NULL,
	sinopsis text NULL,
	director varchar(80) NULL,
	fecha_alquiler date NULL,
	fecha_devolucion date NULL
);

INSERT INTO tmp_videoclub (id_copia,fecha_alquiler_texto,dni,nombre,apellido_1,apellido_2,email,telefono,codigo_postal,fecha_nacimiento,numero,piso,letra,calle,ext,titulo,genero,sinopsis,director,fecha_alquiler,fecha_devolucion) VALUES
	 (3,'2024-01-28','1124603H','Ivan','Santana','Medina','ivan.santana.medina@gmail.com','694804631','47007','2005-02-15','6','3','D','Francisco Pizarro','3D','El padrino','Drama','Don Vito Corleone, conocido dentro de los círculos del hampa como ''El Padrino'', es el patriarca de una de las cinco familias que ejercen el mando de la Cosa Nostra en Nueva York en los años cuarenta. Don Corleone tiene cuatro hijos: una chica, Connie, y tres varones; Sonny, Michael y Fredo. Cuando el Padrino reclina intervenir en el negocio de estupefacientes, empieza una cruenta lucha de violentos episodios entre las distintas familias del crimen organizado.','Francis Ford Coppola','2024-01-28',NULL),
	 (4,'2024-01-30','1396452F','Maria carmen','Crespo','Reyes','maria carmen.crespo.reyes@gmail.com','607425989','47005','2000-11-17','58','1','A','Francisco de Goya','1A','El padrino','Drama','Don Vito Corleone, conocido dentro de los círculos del hampa como ''El Padrino'', es el patriarca de una de las cinco familias que ejercen el mando de la Cosa Nostra en Nueva York en los años cuarenta. Don Corleone tiene cuatro hijos: una chica, Connie, y tres varones; Sonny, Michael y Fredo. Cuando el Padrino reclina intervenir en el negocio de estupefacientes, empieza una cruenta lucha de violentos episodios entre las distintas familias del crimen organizado.','Francis Ford Coppola','2024-01-30','2024-01-31'),
	 (4,'2024-02-01','6162443F','Rodrigo','Muñoz','Muñoz','rodrigo.muñoz.muñoz@gmail.com','607661550','47001','2006-10-23','51','1','A','Antonio Machado','1A','El padrino','Drama','Don Vito Corleone, conocido dentro de los círculos del hampa como ''El Padrino'', es el patriarca de una de las cinco familias que ejercen el mando de la Cosa Nostra en Nueva York en los años cuarenta. Don Corleone tiene cuatro hijos: una chica, Connie, y tres varones; Sonny, Michael y Fredo. Cuando el Padrino reclina intervenir en el negocio de estupefacientes, empieza una cruenta lucha de violentos episodios entre las distintas familias del crimen organizado.','Francis Ford Coppola','2024-02-01',NULL),
	 (5,'2024-01-10','3913881V','Maria pilar','Gallego','Moya','maria pilar.gallego.moya@gmail.com','611154361','47003','2015-03-22','86','3','B','Iglesia','3B','El padrino. Parte II','Drama','Continuación de la saga de los Corleone con dos historias paralelas: la elección de Michael Corleone como jefe de los negocios familiares y los orígenes del patriarca, el ya fallecido Don Vito, primero en Sicilia y luego en Estados Unidos, donde, empezando desde abajo, llegó a ser un poderosísimo jefe de la mafia de Nueva York.','Francis Ford Coppola','2024-01-10',NULL),
	 (6,'2024-01-04','8568516G','Carla','Rojas','Pastor','carla.rojas.pastor@gmail.com','613713642','47008','1990-10-12','65','3','D','Hernán Cortés','3D','El padrino. Parte II','Drama','Continuación de la saga de los Corleone con dos historias paralelas: la elección de Michael Corleone como jefe de los negocios familiares y los orígenes del patriarca, el ya fallecido Don Vito, primero en Sicilia y luego en Estados Unidos, donde, empezando desde abajo, llegó a ser un poderosísimo jefe de la mafia de Nueva York.','Francis Ford Coppola','2024-01-04',NULL),
	 (7,'2024-01-13','7402615L','Eva','Hidalgo','Cortes','eva.hidalgo.cortes@gmail.com','666238181','47003','2010-09-02','57','2','A','Fuente','2A','El padrino. Parte II','Drama','Continuación de la saga de los Corleone con dos historias paralelas: la elección de Michael Corleone como jefe de los negocios familiares y los orígenes del patriarca, el ya fallecido Don Vito, primero en Sicilia y luego en Estados Unidos, donde, empezando desde abajo, llegó a ser un poderosísimo jefe de la mafia de Nueva York.','Francis Ford Coppola','2024-01-13',NULL),
	 (8,'2024-01-24','8344064D','Lidia','Calvo','Iglesias','lidia.calvo.iglesias@gmail.com','641396802','47002','1998-03-09','99','1','Der.','Clara Campoamor','1Der.','La lista de Schindler','Drama','Oskar Schindler, un hombre de enorme astucia y talento para las relaciones públicas, organiza un ambicioso plan para ganarse la simpatía de los nazis. Después de la invasión de Polonia por los alemanes, consigue, gracias a sus relaciones con los nazis, la propiedad de una fábrica de Cracovia. Allí emplea a cientos de operarios judíos, cuya explotación le hace prosperar rápidamente. Su gerente, también judío, es el verdadero director en la sombra, pues Schindler no tiene el menor conocimiento industrial.','Steven Spielberg','2024-01-24','2024-01-25'),
	 (63,'2024-01-24','6298662C','Angela','Lopez','Rubio','angela.lopez.rubio@gmail.com','628535856','47001','1992-06-26','37','3','Der.','Real','3Der.','Taylor Swift: Gira de estadios Reputation','Musical','Taylor Swift se sube al escenario en Dallas durante su Reputation Stadium Tour y festeja una gran noche de música, recuerdos y magia visual.','Paul Dugdale','2024-01-24','2024-01-25'),
	 (8,'2024-01-27','6298662C','Angela','Lopez','Rubio','angela.lopez.rubio@gmail.com','628535856','47001','1992-06-26','37','3','Der.','Real','3Der.','La lista de Schindler','Drama','Oskar Schindler, un hombre de enorme astucia y talento para las relaciones públicas, organiza un ambicioso plan para ganarse la simpatía de los nazis. Después de la invasión de Polonia por los alemanes, consigue, gracias a sus relaciones con los nazis, la propiedad de una fábrica de Cracovia. Allí emplea a cientos de operarios judíos, cuya explotación le hace prosperar rápidamente. Su gerente, también judío, es el verdadero director en la sombra, pues Schindler no tiene el menor conocimiento industrial.','Steven Spielberg','2024-01-27','2024-01-28'),
	 (8,'2024-02-02','2237186E','Eduardo','Alonso','Castro','eduardo.alonso.castro@gmail.com','684839436','47007','1999-07-25','12','1','D','Reina Sofía','1D','La lista de Schindler','Drama','Oskar Schindler, un hombre de enorme astucia y talento para las relaciones públicas, organiza un ambicioso plan para ganarse la simpatía de los nazis. Después de la invasión de Polonia por los alemanes, consigue, gracias a sus relaciones con los nazis, la propiedad de una fábrica de Cracovia. Allí emplea a cientos de operarios judíos, cuya explotación le hace prosperar rápidamente. Su gerente, también judío, es el verdadero director en la sombra, pues Schindler no tiene el menor conocimiento industrial.','Steven Spielberg','2024-02-02',NULL),
	 (9,'2024-01-30','8568516G','Carla','Rojas','Pastor','carla.rojas.pastor@gmail.com','613713642','47008','1990-10-12','65','3','D','Hernán Cortés','3D','La lista de Schindler','Drama','Oskar Schindler, un hombre de enorme astucia y talento para las relaciones públicas, organiza un ambicioso plan para ganarse la simpatía de los nazis. Después de la invasión de Polonia por los alemanes, consigue, gracias a sus relaciones con los nazis, la propiedad de una fábrica de Cracovia. Allí emplea a cientos de operarios judíos, cuya explotación le hace prosperar rápidamente. Su gerente, también judío, es el verdadero director en la sombra, pues Schindler no tiene el menor conocimiento industrial.','Steven Spielberg','2024-01-30','2024-01-31'),
	 (9,'2024-02-01','6152776T','Margarita','Nuñez','Fuentes','margarita.nuñez.fuentes@gmail.com','614215413','47007','1998-03-02','62','2','Izq.','Bartolomé Esteban Murillo','2Izq.','La lista de Schindler','Drama','Oskar Schindler, un hombre de enorme astucia y talento para las relaciones públicas, organiza un ambicioso plan para ganarse la simpatía de los nazis. Después de la invasión de Polonia por los alemanes, consigue, gracias a sus relaciones con los nazis, la propiedad de una fábrica de Cracovia. Allí emplea a cientos de operarios judíos, cuya explotación le hace prosperar rápidamente. Su gerente, también judío, es el verdadero director en la sombra, pues Schindler no tiene el menor conocimiento industrial.','Steven Spielberg','2024-02-01',NULL),
	 (10,'2024-01-11','6098616M','Javier','Dominguez','Lozano','javier.dominguez.lozano@gmail.com','616805343','47008','2010-11-03','42','2','Der.','María Zambrano','2Der.','La lista de Schindler','Drama','Oskar Schindler, un hombre de enorme astucia y talento para las relaciones públicas, organiza un ambicioso plan para ganarse la simpatía de los nazis. Después de la invasión de Polonia por los alemanes, consigue, gracias a sus relaciones con los nazis, la propiedad de una fábrica de Cracovia. Allí emplea a cientos de operarios judíos, cuya explotación le hace prosperar rápidamente. Su gerente, también judío, es el verdadero director en la sombra, pues Schindler no tiene el menor conocimiento industrial.','Steven Spielberg','2024-01-11',NULL),
	 (11,'2024-01-14','8344064D','Lidia','Calvo','Iglesias','lidia.calvo.iglesias@gmail.com','641396802','47002','1998-03-09','99','1','Der.','Clara Campoamor','1Der.','La lista de Schindler','Drama','Oskar Schindler, un hombre de enorme astucia y talento para las relaciones públicas, organiza un ambicioso plan para ganarse la simpatía de los nazis. Después de la invasión de Polonia por los alemanes, consigue, gracias a sus relaciones con los nazis, la propiedad de una fábrica de Cracovia. Allí emplea a cientos de operarios judíos, cuya explotación le hace prosperar rápidamente. Su gerente, también judío, es el verdadero director en la sombra, pues Schindler no tiene el menor conocimiento industrial.','Steven Spielberg','2024-01-14',NULL),
	 (12,'2024-02-02','7402615L','Eva','Hidalgo','Cortes','eva.hidalgo.cortes@gmail.com','666238181','47003','2010-09-02','57','2','A','Fuente','2A','12 hombres sin piedad','Drama','Tras escuchar todos los testimonios y valorar las pruebas presentadas, un jurado popular compuesto por doce hombres tiene que decidir, por unanimidad, si absuelve o condena a muerte a un joven acusado de haber matado a su padre. Al principio, once están completamente convencidos de su culpabilidad y se inclinan por la condena, pero el que discrepa empieza a plantear dudas razonables que, poco a poco, van resquebrajando la inicial seguridad de los demás.','Sidney Lumet','2024-02-02',NULL),
	 (13,'2024-01-04','6938009J','Xavier','Caballero','Fuentes','xavier.caballero.fuentes@gmail.com','671280006','47004','2000-02-05','89','1','B','Iglesia','1B','12 hombres sin piedad','Drama','Tras escuchar todos los testimonios y valorar las pruebas presentadas, un jurado popular compuesto por doce hombres tiene que decidir, por unanimidad, si absuelve o condena a muerte a un joven acusado de haber matado a su padre. Al principio, once están completamente convencidos de su culpabilidad y se inclinan por la condena, pero el que discrepa empieza a plantear dudas razonables que, poco a poco, van resquebrajando la inicial seguridad de los demás.','Sidney Lumet','2024-01-04','2024-01-05'),
	 (13,'2024-01-17','3913881V','Maria pilar','Gallego','Moya','maria pilar.gallego.moya@gmail.com','611154361','47003','2015-03-22','86','3','B','Iglesia','3B','12 hombres sin piedad','Drama','Tras escuchar todos los testimonios y valorar las pruebas presentadas, un jurado popular compuesto por doce hombres tiene que decidir, por unanimidad, si absuelve o condena a muerte a un joven acusado de haber matado a su padre. Al principio, once están completamente convencidos de su culpabilidad y se inclinan por la condena, pero el que discrepa empieza a plantear dudas razonables que, poco a poco, van resquebrajando la inicial seguridad de los demás.','Sidney Lumet','2024-01-17',NULL),
	 (14,'2024-01-08','8552386C','Domingo','Mora','Ibañez','domingo.mora.ibañez@gmail.com','618225142','47000','2000-04-08','57','4','B','Reina Sofía','4B','12 hombres sin piedad','Drama','Tras escuchar todos los testimonios y valorar las pruebas presentadas, un jurado popular compuesto por doce hombres tiene que decidir, por unanimidad, si absuelve o condena a muerte a un joven acusado de haber matado a su padre. Al principio, once están completamente convencidos de su culpabilidad y se inclinan por la condena, pero el que discrepa empieza a plantear dudas razonables que, poco a poco, van resquebrajando la inicial seguridad de los demás.','Sidney Lumet','2024-01-08',NULL),
	 (15,'2024-01-22','6098616M','Javier','Dominguez','Lozano','javier.dominguez.lozano@gmail.com','616805343','47008','2010-11-03','42','2','Der.','María Zambrano','2Der.','12 hombres sin piedad','Drama','Tras escuchar todos los testimonios y valorar las pruebas presentadas, un jurado popular compuesto por doce hombres tiene que decidir, por unanimidad, si absuelve o condena a muerte a un joven acusado de haber matado a su padre. Al principio, once están completamente convencidos de su culpabilidad y se inclinan por la condena, pero el que discrepa empieza a plantear dudas razonables que, poco a poco, van resquebrajando la inicial seguridad de los demás.','Sidney Lumet','2024-01-22',NULL),
	 (63,'2024-01-28','9554616W','Ana maria','Flores','Marin','ana maria.flores.marin@gmail.com','681962651','47008','1991-08-23','99','3','B','Ramón y Cajal','3B','Taylor Swift: Gira de estadios Reputation','Musical','Taylor Swift se sube al escenario en Dallas durante su Reputation Stadium Tour y festeja una gran noche de música, recuerdos y magia visual.','Paul Dugdale','2024-01-28',NULL),
	 (16,'2024-01-10','8597459J','Jaime','Cruz','Calvo','jaime.cruz.calvo@gmail.com','617112942','47003','2005-01-05','87','4','Izq.','Iglesia','4Izq.','Un amor contra viento y marea','Comedia','Los Singh son una familia india con grandes convicciones culturales de su nación de origen, que emigraron a Reino Unido antes de nacer sus primeros hijos. Uno de ellos querrá casarse con una mujer ajena a su cultura y para ello deberá hacer todos los esfuerzos por convencer a su familia.','Aditya Chopra','2024-01-10',NULL),
	 (17,'2024-01-02','2285124M','Jose ignacio','Rojas','Blanco','jose ignacio.rojas.blanco@gmail.com','604696806','47007','2010-11-06','57','4','A','Concepción Arenal','4A','Un amor contra viento y marea','Comedia','Los Singh son una familia india con grandes convicciones culturales de su nación de origen, que emigraron a Reino Unido antes de nacer sus primeros hijos. Uno de ellos querrá casarse con una mujer ajena a su cultura y para ello deberá hacer todos los esfuerzos por convencer a su familia.','Aditya Chopra','2024-01-02',NULL),
	 (18,'2024-01-06','8843886H','Jaime','Rojas','Gimenez','jaime.rojas.gimenez@gmail.com','600852997','47009','2011-08-28','38','4','C','Constitución','4C','El viaje de Chihiro','Animación','Durante el traslado de su familia a los suburbios, una niña de 10 años de edad deambula por un mundo gobernado por dioses, brujas y espíritus, y donde los humanos se convierten en bestias.','Hayao Miyazaki','2024-01-06',NULL),
	 (19,'2024-01-22','4426152D','Adrian','Gil','Fernandez','adrian.gil.fernandez@gmail.com','675655492','47002','1995-03-21','64','4','A','Francisco de Goya','4A','El viaje de Chihiro','Animación','Durante el traslado de su familia a los suburbios, una niña de 10 años de edad deambula por un mundo gobernado por dioses, brujas y espíritus, y donde los humanos se convierten en bestias.','Hayao Miyazaki','2024-01-22',NULL),
	 (20,'2024-01-29','8597459J','Jaime','Cruz','Calvo','jaime.cruz.calvo@gmail.com','617112942','47003','2005-01-05','87','4','Izq.','Iglesia','4Izq.','El viaje de Chihiro','Animación','Durante el traslado de su familia a los suburbios, una niña de 10 años de edad deambula por un mundo gobernado por dioses, brujas y espíritus, y donde los humanos se convierten en bestias.','Hayao Miyazaki','2024-01-29',NULL),
	 (21,'2024-01-05','5653366N','Maria nieves','Lozano','Leon','maria nieves.lozano.leon@gmail.com','680082585','47003','2002-01-06','21','2','Der.','Hernán Cortés','2Der.','El viaje de Chihiro','Animación','Durante el traslado de su familia a los suburbios, una niña de 10 años de edad deambula por un mundo gobernado por dioses, brujas y espíritus, y donde los humanos se convierten en bestias.','Hayao Miyazaki','2024-01-05',NULL),
	 (22,'2024-01-08','2237186E','Eduardo','Alonso','Castro','eduardo.alonso.castro@gmail.com','684839436','47007','1999-07-25','12','1','D','Reina Sofía','1D','El caballero oscuro','Drama','Batman/Bruce Wayne regresa para continuar su guerra contra el crimen. Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman se propone destruir el crimen organizado en la ciudad de Gotham. El triunvirato demuestra su eficacia, pero, de repente, aparece Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.','Christopher Nolan','2024-01-08',NULL),
	 (23,'2024-01-21','6121885K','Joaquin','Gil','Diaz','joaquin.gil.diaz@gmail.com','610203487','47005','2009-07-29','13','4','A','Miguel de Cervantes','4A','El caballero oscuro','Drama','Batman/Bruce Wayne regresa para continuar su guerra contra el crimen. Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman se propone destruir el crimen organizado en la ciudad de Gotham. El triunvirato demuestra su eficacia, pero, de repente, aparece Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.','Christopher Nolan','2024-01-21','2024-01-22'),
	 (51,'2024-01-15','9707193C','Aitor','Herrera','Roman','aitor.herrera.roman@gmail.com','646020411','47000','1992-04-23','77','3','Izq.','Rosalía de Castro','3Izq.','Los siete samuráis','Acción','Una banda de forajidos atemorizan a los habitantes de un pequeño pueblo, saqueándolos periódicamente sin piedad. Para repeler estos ataques, los aldeanos deciden contratar a mercenarios. Finalmente, consiguen los servicios de 7 guerreros, 7 samurais dispuestos a defenderlos a cambio, tan solo, de cobijo y comida.','Akira Kurosawa','2024-01-15','2024-01-16'),
	 (23,'2024-01-24','2537526M','Jose antonio','Guerrero','Molina','jose antonio.guerrero.molina@gmail.com','675872614','47007','1991-11-30','17','3','Izq.','Dulcinea','3Izq.','El caballero oscuro','Drama','Batman/Bruce Wayne regresa para continuar su guerra contra el crimen. Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman se propone destruir el crimen organizado en la ciudad de Gotham. El triunvirato demuestra su eficacia, pero, de repente, aparece Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.','Christopher Nolan','2024-01-24','2024-01-25'),
	 (23,'2024-02-01','7719170W','Aitor','Ibañez','Morales','aitor.ibañez.morales@gmail.com','683249365','47009','2002-02-04','49','1','Der.','María Zambrano','1Der.','El caballero oscuro','Drama','Batman/Bruce Wayne regresa para continuar su guerra contra el crimen. Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman se propone destruir el crimen organizado en la ciudad de Gotham. El triunvirato demuestra su eficacia, pero, de repente, aparece Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.','Christopher Nolan','2024-02-01',NULL),
	 (24,'2024-01-28','7158923N','Paula','Campos','Navarro','paula.campos.navarro@gmail.com','649523596','47005','2016-09-29','92','1','B','Hernán Cortés','1B','El caballero oscuro','Drama','Batman/Bruce Wayne regresa para continuar su guerra contra el crimen. Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman se propone destruir el crimen organizado en la ciudad de Gotham. El triunvirato demuestra su eficacia, pero, de repente, aparece Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.','Christopher Nolan','2024-01-28','2024-01-29'),
	 (24,'2024-01-31','4426152D','Adrian','Gil','Fernandez','adrian.gil.fernandez@gmail.com','675655492','47002','1995-03-21','64','4','A','Francisco de Goya','4A','El caballero oscuro','Drama','Batman/Bruce Wayne regresa para continuar su guerra contra el crimen. Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman se propone destruir el crimen organizado en la ciudad de Gotham. El triunvirato demuestra su eficacia, pero, de repente, aparece Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.','Christopher Nolan','2024-01-31',NULL),
	 (25,'2024-01-14','6121885K','Joaquin','Gil','Diaz','joaquin.gil.diaz@gmail.com','610203487','47005','2009-07-29','13','4','A','Miguel de Cervantes','4A','Parásitos','Comedia','Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a recibir clases particulares en casa de Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, comienzan una interrelación de resultados imprevisibles.','Bong Joon-ho','2024-01-14','2024-01-15'),
	 (25,'2024-01-19','5125350F','Jose','Saez','Garcia','jose.saez.garcia@gmail.com','637666889','47001','2016-10-05','50','4','Der.','Real','4Der.','Parásitos','Comedia','Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a recibir clases particulares en casa de Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, comienzan una interrelación de resultados imprevisibles.','Bong Joon-ho','2024-01-19',NULL),
	 (26,'2024-01-13','3252617A','Pilar','Marquez','Lozano','pilar.marquez.lozano@gmail.com','621541699','47000','2000-07-13','95','1','B','Eras','1B','Parásitos','Comedia','Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a recibir clases particulares en casa de Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, comienzan una interrelación de resultados imprevisibles.','Bong Joon-ho','2024-01-13','2024-01-14'),
	 (26,'2024-01-22','3252617A','Pilar','Marquez','Lozano','pilar.marquez.lozano@gmail.com','621541699','47000','2000-07-13','95','1','B','Eras','1B','Parásitos','Comedia','Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a recibir clases particulares en casa de Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, comienzan una interrelación de resultados imprevisibles.','Bong Joon-ho','2024-01-22','2024-01-23'),
	 (26,'2024-01-30','4437589S','Pedro','Iglesias','Garrido','pedro.iglesias.garrido@gmail.com','634143203','47000','1999-12-02','34','1','B','Federico García Lorca','1B','Parásitos','Comedia','Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a recibir clases particulares en casa de Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, comienzan una interrelación de resultados imprevisibles.','Bong Joon-ho','2024-01-30',NULL),
	 (27,'2024-01-14','1396452F','Maria carmen','Crespo','Reyes','maria carmen.crespo.reyes@gmail.com','607425989','47005','2000-11-17','58','1','A','Francisco de Goya','1A','La milla verde','Fantasía','En el sur de los Estados Unidos, en plena Depresión, Paul Edgecomb es un vigilante penitenciario a cargo de la Milla Verde, un pasillo que separa las celdas de los reclusos condenados a la silla eléctrica. Esperando su ejecución está John Coffey, un gigantesco negro acusado de asesinar brutalmente a dos hermanas de nueve años. Tras una personalidad ingenua, Coffey esconde un don sobrenatural prodigioso. A medida que transcurre la historia, Paul Edgecomb aprende que los milagros ocurren... incluso en los lugares más insospechados.','Frank Darabont','2024-01-14','2024-01-15'),
	 (27,'2024-01-26','2950461K','Maria rosa','Herrera','Nuñez','maria rosa.herrera.nuñez@gmail.com','674343471','47003','2003-07-24','76','3','D','Pablo Picasso','3D','La milla verde','Fantasía','En el sur de los Estados Unidos, en plena Depresión, Paul Edgecomb es un vigilante penitenciario a cargo de la Milla Verde, un pasillo que separa las celdas de los reclusos condenados a la silla eléctrica. Esperando su ejecución está John Coffey, un gigantesco negro acusado de asesinar brutalmente a dos hermanas de nueve años. Tras una personalidad ingenua, Coffey esconde un don sobrenatural prodigioso. A medida que transcurre la historia, Paul Edgecomb aprende que los milagros ocurren... incluso en los lugares más insospechados.','Frank Darabont','2024-01-26',NULL),
	 (28,'2024-01-03','7719170W','Aitor','Ibañez','Morales','aitor.ibañez.morales@gmail.com','683249365','47009','2002-02-04','49','1','Der.','María Zambrano','1Der.','La milla verde','Fantasía','En el sur de los Estados Unidos, en plena Depresión, Paul Edgecomb es un vigilante penitenciario a cargo de la Milla Verde, un pasillo que separa las celdas de los reclusos condenados a la silla eléctrica. Esperando su ejecución está John Coffey, un gigantesco negro acusado de asesinar brutalmente a dos hermanas de nueve años. Tras una personalidad ingenua, Coffey esconde un don sobrenatural prodigioso. A medida que transcurre la historia, Paul Edgecomb aprende que los milagros ocurren... incluso en los lugares más insospechados.','Frank Darabont','2024-01-03','2024-01-04'),
	 (28,'2024-01-10','5125350F','Jose','Saez','Garcia','jose.saez.garcia@gmail.com','637666889','47001','2016-10-05','50','4','Der.','Real','4Der.','La milla verde','Fantasía','En el sur de los Estados Unidos, en plena Depresión, Paul Edgecomb es un vigilante penitenciario a cargo de la Milla Verde, un pasillo que separa las celdas de los reclusos condenados a la silla eléctrica. Esperando su ejecución está John Coffey, un gigantesco negro acusado de asesinar brutalmente a dos hermanas de nueve años. Tras una personalidad ingenua, Coffey esconde un don sobrenatural prodigioso. A medida que transcurre la historia, Paul Edgecomb aprende que los milagros ocurren... incluso en los lugares más insospechados.','Frank Darabont','2024-01-10',NULL),
	 (29,'2024-01-13','6098616M','Javier','Dominguez','Lozano','javier.dominguez.lozano@gmail.com','616805343','47008','2010-11-03','42','2','Der.','María Zambrano','2Der.','La milla verde','Fantasía','En el sur de los Estados Unidos, en plena Depresión, Paul Edgecomb es un vigilante penitenciario a cargo de la Milla Verde, un pasillo que separa las celdas de los reclusos condenados a la silla eléctrica. Esperando su ejecución está John Coffey, un gigantesco negro acusado de asesinar brutalmente a dos hermanas de nueve años. Tras una personalidad ingenua, Coffey esconde un don sobrenatural prodigioso. A medida que transcurre la historia, Paul Edgecomb aprende que los milagros ocurren... incluso en los lugares más insospechados.','Frank Darabont','2024-01-13',NULL),
	 (30,'2024-01-08','5396546X','Josefa','Rivera','Saez','josefa.rivera.saez@gmail.com','656840966','47004','2016-08-01','38','2','Der.','Dolores Ibárruri','2Der.','La milla verde','Fantasía','En el sur de los Estados Unidos, en plena Depresión, Paul Edgecomb es un vigilante penitenciario a cargo de la Milla Verde, un pasillo que separa las celdas de los reclusos condenados a la silla eléctrica. Esperando su ejecución está John Coffey, un gigantesco negro acusado de asesinar brutalmente a dos hermanas de nueve años. Tras una personalidad ingenua, Coffey esconde un don sobrenatural prodigioso. A medida que transcurre la historia, Paul Edgecomb aprende que los milagros ocurren... incluso en los lugares más insospechados.','Frank Darabont','2024-01-08',NULL),
	 (31,'2024-01-06','4652257R','Jose ignacio','Rodriguez','Gallardo','jose ignacio.rodriguez.gallardo@gmail.com','628297793','47009','1998-01-12','70','2','D','Fuente','2D','Your Name','Romántica','Taki y Mitsuha descubren un día que durante el sueño sus cuerpos se intercambian, y comienzan a comunicarse por medio de notas. A medida que consiguen superar torpemente un reto tras otro, se va creando entre los dos un vínculo que poco a poco se convierte en algo más romántico.','Makoto Shinkai','2024-01-06',NULL),
	 (32,'2024-02-01','7281621M','Jorge','Mendez','Alvarez','jorge.mendez.alvarez@gmail.com','615944300','47006','2002-05-26','56','3','Izq.','Sol','3Izq.','Your Name','Romántica','Taki y Mitsuha descubren un día que durante el sueño sus cuerpos se intercambian, y comienzan a comunicarse por medio de notas. A medida que consiguen superar torpemente un reto tras otro, se va creando entre los dos un vínculo que poco a poco se convierte en algo más romántico.','Makoto Shinkai','2024-02-01',NULL),
	 (33,'2024-01-21','7070649N','Albert','Cruz','Gomez','albert.cruz.gomez@gmail.com','632333185','47006','2015-02-23','3','3','C','Constitución','3C','Your Name','Romántica','Taki y Mitsuha descubren un día que durante el sueño sus cuerpos se intercambian, y comienzan a comunicarse por medio de notas. A medida que consiguen superar torpemente un reto tras otro, se va creando entre los dos un vínculo que poco a poco se convierte en algo más romántico.','Makoto Shinkai','2024-01-21',NULL),
	 (34,'2024-01-12','7386143S','Marta','Santiago','Rubio','marta.santiago.rubio@gmail.com','667115015','47006','2017-03-01','71','2','D','Mariana Pineda','2D','Your Name','Romántica','Taki y Mitsuha descubren un día que durante el sueño sus cuerpos se intercambian, y comienzan a comunicarse por medio de notas. A medida que consiguen superar torpemente un reto tras otro, se va creando entre los dos un vínculo que poco a poco se convierte en algo más romántico.','Makoto Shinkai','2024-01-12','2024-01-13'),
	 (34,'2024-01-13','2475849Z','Adrian','Santiago','Roman','adrian.santiago.roman@gmail.com','699684082','47001','2006-12-20','44','1','D','Agustina de Aragón','1D','Your Name','Romántica','Taki y Mitsuha descubren un día que durante el sueño sus cuerpos se intercambian, y comienzan a comunicarse por medio de notas. A medida que consiguen superar torpemente un reto tras otro, se va creando entre los dos un vínculo que poco a poco se convierte en algo más romántico.','Makoto Shinkai','2024-01-13','2024-01-14'),
	 (34,'2024-01-30','1638778M','Angel','Lorenzo','Caballero','angel.lorenzo.caballero@gmail.com','698073069','47008','2011-07-30','82','1','Izq.','Sol','1Izq.','Your Name','Romántica','Taki y Mitsuha descubren un día que durante el sueño sus cuerpos se intercambian, y comienzan a comunicarse por medio de notas. A medida que consiguen superar torpemente un reto tras otro, se va creando entre los dos un vínculo que poco a poco se convierte en algo más romántico.','Makoto Shinkai','2024-01-30','2024-01-31'),
	 (34,'2024-02-01','6298662C','Angela','Lopez','Rubio','angela.lopez.rubio@gmail.com','628535856','47001','1992-06-26','37','3','Der.','Real','3Der.','Your Name','Romántica','Taki y Mitsuha descubren un día que durante el sueño sus cuerpos se intercambian, y comienzan a comunicarse por medio de notas. A medida que consiguen superar torpemente un reto tras otro, se va creando entre los dos un vínculo que poco a poco se convierte en algo más romántico.','Makoto Shinkai','2024-02-01',NULL),
	 (35,'2024-01-16','2285124M','Jose ignacio','Rojas','Blanco','jose ignacio.rojas.blanco@gmail.com','604696806','47007','2010-11-06','57','4','A','Concepción Arenal','4A','Pulp Fiction','Thriller','Jules y Vincent, dos asesinos a sueldo con muy pocas luces, trabajan para Marsellus Wallace. Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe. Cuando llega la hora de trabajar, ambos deben ponerse manos a la obra. Su misión: recuperar un misterioso maletín.','Quentin Tarantino','2024-01-16','2024-01-17'),
	 (35,'2024-02-01','7402615L','Eva','Hidalgo','Cortes','eva.hidalgo.cortes@gmail.com','666238181','47003','2010-09-02','57','2','A','Fuente','2A','Pulp Fiction','Thriller','Jules y Vincent, dos asesinos a sueldo con muy pocas luces, trabajan para Marsellus Wallace. Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe. Cuando llega la hora de trabajar, ambos deben ponerse manos a la obra. Su misión: recuperar un misterioso maletín.','Quentin Tarantino','2024-02-01',NULL),
	 (36,'2024-01-27','5653366N','Maria nieves','Lozano','Leon','maria nieves.lozano.leon@gmail.com','680082585','47003','2002-01-06','21','2','Der.','Hernán Cortés','2Der.','Pulp Fiction','Thriller','Jules y Vincent, dos asesinos a sueldo con muy pocas luces, trabajan para Marsellus Wallace. Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe. Cuando llega la hora de trabajar, ambos deben ponerse manos a la obra. Su misión: recuperar un misterioso maletín.','Quentin Tarantino','2024-01-27','2024-01-28'),
	 (36,'2024-01-29','6162443F','Rodrigo','Muñoz','Muñoz','rodrigo.muñoz.muñoz@gmail.com','607661550','47001','2006-10-23','51','1','A','Antonio Machado','1A','Pulp Fiction','Thriller','Jules y Vincent, dos asesinos a sueldo con muy pocas luces, trabajan para Marsellus Wallace. Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe. Cuando llega la hora de trabajar, ambos deben ponerse manos a la obra. Su misión: recuperar un misterioso maletín.','Quentin Tarantino','2024-01-29','2024-01-30'),
	 (36,'2024-01-30','9737608Y','Jose angel','Crespo','Nuñez','jose angel.crespo.nuñez@gmail.com','669370813','47003','2016-10-07','24','1','Izq.','Emilia Pardo Bazán','1Izq.','Pulp Fiction','Thriller','Jules y Vincent, dos asesinos a sueldo con muy pocas luces, trabajan para Marsellus Wallace. Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe. Cuando llega la hora de trabajar, ambos deben ponerse manos a la obra. Su misión: recuperar un misterioso maletín.','Quentin Tarantino','2024-01-30','2024-01-31'),
	 (36,'2024-02-02','6121885K','Joaquin','Gil','Diaz','joaquin.gil.diaz@gmail.com','610203487','47005','2009-07-29','13','4','A','Miguel de Cervantes','4A','Pulp Fiction','Thriller','Jules y Vincent, dos asesinos a sueldo con muy pocas luces, trabajan para Marsellus Wallace. Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe. Cuando llega la hora de trabajar, ambos deben ponerse manos a la obra. Su misión: recuperar un misterioso maletín.','Quentin Tarantino','2024-02-02',NULL),
	 (37,'2024-01-21','6648907K','Jose antonio','Moya','Morales','jose antonio.moya.morales@gmail.com','688827827','47004','2008-01-23','33','2','C','Francisco de Goya','2C','Pulp Fiction','Thriller','Jules y Vincent, dos asesinos a sueldo con muy pocas luces, trabajan para Marsellus Wallace. Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe. Cuando llega la hora de trabajar, ambos deben ponerse manos a la obra. Su misión: recuperar un misterioso maletín.','Quentin Tarantino','2024-01-21',NULL),
	 (38,'2024-01-25','2537526M','Jose antonio','Guerrero','Molina','jose antonio.guerrero.molina@gmail.com','675872614','47007','1991-11-30','17','3','Izq.','Dulcinea','3Izq.','El señor de los anillos: El retorno del rey','Aventura','Las fuerzas de Saruman han sido destruidas, y su fortaleza sitiada. Ha llegado el momento de que se decida el destino de la Tierra Media, y por primera vez en mucho tiempo, parece que hay una pequeña esperanza. La atención del señor oscuro Sauron se centra ahora en Gondor, el último reducto de los hombres, y del cual Aragorn tendrá que reclamar el trono para ocupar su puesto de rey. Pero las fuerzas de Sauron ya se preparan para lanzar el último y definitivo ataque contra el reino de Gondor, la batalla que decidirá el destino de todos. Mientras tanto, Frodo y Sam continuan su camino hacia Mordor, a la espera de que Sauron no repare en que dos pequeños Hobbits se acercan cada día más al final de su camino, el Monte del Destino.','Peter Jackson','2024-01-25',NULL),
	 (39,'2024-01-22','6152776T','Margarita','Nuñez','Fuentes','margarita.nuñez.fuentes@gmail.com','614215413','47007','1998-03-02','62','2','Izq.','Bartolomé Esteban Murillo','2Izq.','El señor de los anillos: El retorno del rey','Aventura','Las fuerzas de Saruman han sido destruidas, y su fortaleza sitiada. Ha llegado el momento de que se decida el destino de la Tierra Media, y por primera vez en mucho tiempo, parece que hay una pequeña esperanza. La atención del señor oscuro Sauron se centra ahora en Gondor, el último reducto de los hombres, y del cual Aragorn tendrá que reclamar el trono para ocupar su puesto de rey. Pero las fuerzas de Sauron ya se preparan para lanzar el último y definitivo ataque contra el reino de Gondor, la batalla que decidirá el destino de todos. Mientras tanto, Frodo y Sam continuan su camino hacia Mordor, a la espera de que Sauron no repare en que dos pequeños Hobbits se acercan cada día más al final de su camino, el Monte del Destino.','Peter Jackson','2024-01-22','2024-01-23'),
	 (39,'2024-02-02','2237186E','Eduardo','Alonso','Castro','eduardo.alonso.castro@gmail.com','684839436','47007','1999-07-25','12','1','D','Reina Sofía','1D','El señor de los anillos: El retorno del rey','Aventura','Las fuerzas de Saruman han sido destruidas, y su fortaleza sitiada. Ha llegado el momento de que se decida el destino de la Tierra Media, y por primera vez en mucho tiempo, parece que hay una pequeña esperanza. La atención del señor oscuro Sauron se centra ahora en Gondor, el último reducto de los hombres, y del cual Aragorn tendrá que reclamar el trono para ocupar su puesto de rey. Pero las fuerzas de Sauron ya se preparan para lanzar el último y definitivo ataque contra el reino de Gondor, la batalla que decidirá el destino de todos. Mientras tanto, Frodo y Sam continuan su camino hacia Mordor, a la espera de que Sauron no repare en que dos pequeños Hobbits se acercan cada día más al final de su camino, el Monte del Destino.','Peter Jackson','2024-02-02',NULL),
	 (74,'2024-01-04','6298662C','Angela','Lopez','Rubio','angela.lopez.rubio@gmail.com','628535856','47001','1992-06-26','37','3','Der.','Real','3Der.','Gabriel''s Inferno','Romántica','El enigmático y atractivo profesor Gabriel Emerson, reconocido especialista en Dante, es un hombre torturado por su pasado y orgulloso del prestigio que ha conseguido, aunque también es consciente de que es un imán para el pecado y, en especial, para la lujuria.','Tosca Musk','2024-01-04','2024-01-05'),
	 (40,'2024-01-15','6938009J','Xavier','Caballero','Fuentes','xavier.caballero.fuentes@gmail.com','671280006','47004','2000-02-05','89','1','B','Iglesia','1B','El señor de los anillos: El retorno del rey','Aventura','Las fuerzas de Saruman han sido destruidas, y su fortaleza sitiada. Ha llegado el momento de que se decida el destino de la Tierra Media, y por primera vez en mucho tiempo, parece que hay una pequeña esperanza. La atención del señor oscuro Sauron se centra ahora en Gondor, el último reducto de los hombres, y del cual Aragorn tendrá que reclamar el trono para ocupar su puesto de rey. Pero las fuerzas de Sauron ya se preparan para lanzar el último y definitivo ataque contra el reino de Gondor, la batalla que decidirá el destino de todos. Mientras tanto, Frodo y Sam continuan su camino hacia Mordor, a la espera de que Sauron no repare en que dos pequeños Hobbits se acercan cada día más al final de su camino, el Monte del Destino.','Peter Jackson','2024-01-15',NULL),
	 (41,'2024-01-06','9554616W','Ana maria','Flores','Marin','ana maria.flores.marin@gmail.com','681962651','47008','1991-08-23','99','3','B','Ramón y Cajal','3B','Forrest Gump','Comedia','Forrest Gump es un chico con deficiencias mentales no muy profundas y con alguna incapacidad motora que, a pesar de todo, llegará a convertirse, entre otras cosas, en un héroe durante la Guerra del Vietnam. Su persistencia y bondad le llevarán a conseguir una gran fortuna, ser objeto del clamor popular y a codearse con las más altas esferas sociales y políticas del país. Siempre sin olvidar a Jenny, su gran amor desde que era niño.','Robert Zemeckis','2024-01-06',NULL),
	 (42,'2024-01-13','4435315H','Lidia','Rubio','Benitez','lidia.rubio.benitez@gmail.com','621419327','47003','1993-09-12','91','2','Der.','Concepción Arenal','2Der.','Forrest Gump','Comedia','Forrest Gump es un chico con deficiencias mentales no muy profundas y con alguna incapacidad motora que, a pesar de todo, llegará a convertirse, entre otras cosas, en un héroe durante la Guerra del Vietnam. Su persistencia y bondad le llevarán a conseguir una gran fortuna, ser objeto del clamor popular y a codearse con las más altas esferas sociales y políticas del país. Siempre sin olvidar a Jenny, su gran amor desde que era niño.','Robert Zemeckis','2024-01-13','2024-01-14'),
	 (42,'2024-01-29','8568516G','Carla','Rojas','Pastor','carla.rojas.pastor@gmail.com','613713642','47008','1990-10-12','65','3','D','Hernán Cortés','3D','Forrest Gump','Comedia','Forrest Gump es un chico con deficiencias mentales no muy profundas y con alguna incapacidad motora que, a pesar de todo, llegará a convertirse, entre otras cosas, en un héroe durante la Guerra del Vietnam. Su persistencia y bondad le llevarán a conseguir una gran fortuna, ser objeto del clamor popular y a codearse con las más altas esferas sociales y políticas del país. Siempre sin olvidar a Jenny, su gran amor desde que era niño.','Robert Zemeckis','2024-01-29',NULL),
	 (79,'2024-01-07','9554616W','Ana maria','Flores','Marin','ana maria.flores.marin@gmail.com','681962651','47008','1991-08-23','99','3','B','Ramón y Cajal','3B','Interstellar','Aventura','Narra las aventuras de un grupo de exploradores que hacen uso de un agujero de gusano recientemente descubierto para superar las limitaciones de los viajes espaciales tripulados y vencer las inmensas distancias que tiene un viaje interestelar.','Christopher Nolan','2024-01-07',NULL),
	 (43,'2024-01-20','7719170W','Aitor','Ibañez','Morales','aitor.ibañez.morales@gmail.com','683249365','47009','2002-02-04','49','1','Der.','María Zambrano','1Der.','Forrest Gump','Comedia','Forrest Gump es un chico con deficiencias mentales no muy profundas y con alguna incapacidad motora que, a pesar de todo, llegará a convertirse, entre otras cosas, en un héroe durante la Guerra del Vietnam. Su persistencia y bondad le llevarán a conseguir una gran fortuna, ser objeto del clamor popular y a codearse con las más altas esferas sociales y políticas del país. Siempre sin olvidar a Jenny, su gran amor desde que era niño.','Robert Zemeckis','2024-01-20',NULL),
	 (44,'2024-01-18','2475849Z','Adrian','Santiago','Roman','adrian.santiago.roman@gmail.com','699684082','47001','2006-12-20','44','1','D','Agustina de Aragón','1D','Forrest Gump','Comedia','Forrest Gump es un chico con deficiencias mentales no muy profundas y con alguna incapacidad motora que, a pesar de todo, llegará a convertirse, entre otras cosas, en un héroe durante la Guerra del Vietnam. Su persistencia y bondad le llevarán a conseguir una gran fortuna, ser objeto del clamor popular y a codearse con las más altas esferas sociales y políticas del país. Siempre sin olvidar a Jenny, su gran amor desde que era niño.','Robert Zemeckis','2024-01-18','2024-01-19'),
	 (44,'2024-01-25','2950461K','Maria rosa','Herrera','Nuñez','maria rosa.herrera.nuñez@gmail.com','674343471','47003','2003-07-24','76','3','D','Pablo Picasso','3D','Forrest Gump','Comedia','Forrest Gump es un chico con deficiencias mentales no muy profundas y con alguna incapacidad motora que, a pesar de todo, llegará a convertirse, entre otras cosas, en un héroe durante la Guerra del Vietnam. Su persistencia y bondad le llevarán a conseguir una gran fortuna, ser objeto del clamor popular y a codearse con las más altas esferas sociales y políticas del país. Siempre sin olvidar a Jenny, su gran amor desde que era niño.','Robert Zemeckis','2024-01-25',NULL),
	 (45,'2024-01-19','2475849Z','Adrian','Santiago','Roman','adrian.santiago.roman@gmail.com','699684082','47001','2006-12-20','44','1','D','Agustina de Aragón','1D','El bueno, el feo y el malo','Western','Durante la Guerra de Secesión, tres cazadores de recompensas se lanzan a la búsqueda de un tesoro que ninguno de los tres truhanes puede localizar sin la ayuda de los otros dos. Tuco sabe que el tesoro se encuentra en un cementerio, mientras que Joe conoce el nombre inscrito en la tumba que lo esconde. Mientras tanto, Sentenza no duda en matar a mujeres y niños para conseguir su meta. De esta forma, los tres hombres colaboran en apariencia, pero al final intentarán eliminarse mutuamente.','Sergio Leone','2024-01-19',NULL),
	 (46,'2024-02-01','5125350F','Jose','Saez','Garcia','jose.saez.garcia@gmail.com','637666889','47001','2016-10-05','50','4','Der.','Real','4Der.','El bueno, el feo y el malo','Western','Durante la Guerra de Secesión, tres cazadores de recompensas se lanzan a la búsqueda de un tesoro que ninguno de los tres truhanes puede localizar sin la ayuda de los otros dos. Tuco sabe que el tesoro se encuentra en un cementerio, mientras que Joe conoce el nombre inscrito en la tumba que lo esconde. Mientras tanto, Sentenza no duda en matar a mujeres y niños para conseguir su meta. De esta forma, los tres hombres colaboran en apariencia, pero al final intentarán eliminarse mutuamente.','Sergio Leone','2024-02-01',NULL),
	 (47,'2024-01-29','7402615L','Eva','Hidalgo','Cortes','eva.hidalgo.cortes@gmail.com','666238181','47003','2010-09-02','57','2','A','Fuente','2A','El bueno, el feo y el malo','Western','Durante la Guerra de Secesión, tres cazadores de recompensas se lanzan a la búsqueda de un tesoro que ninguno de los tres truhanes puede localizar sin la ayuda de los otros dos. Tuco sabe que el tesoro se encuentra en un cementerio, mientras que Joe conoce el nombre inscrito en la tumba que lo esconde. Mientras tanto, Sentenza no duda en matar a mujeres y niños para conseguir su meta. De esta forma, los tres hombres colaboran en apariencia, pero al final intentarán eliminarse mutuamente.','Sergio Leone','2024-01-29','2024-01-30'),
	 (47,'2024-01-31','2237186E','Eduardo','Alonso','Castro','eduardo.alonso.castro@gmail.com','684839436','47007','1999-07-25','12','1','D','Reina Sofía','1D','El bueno, el feo y el malo','Western','Durante la Guerra de Secesión, tres cazadores de recompensas se lanzan a la búsqueda de un tesoro que ninguno de los tres truhanes puede localizar sin la ayuda de los otros dos. Tuco sabe que el tesoro se encuentra en un cementerio, mientras que Joe conoce el nombre inscrito en la tumba que lo esconde. Mientras tanto, Sentenza no duda en matar a mujeres y niños para conseguir su meta. De esta forma, los tres hombres colaboran en apariencia, pero al final intentarán eliminarse mutuamente.','Sergio Leone','2024-01-31','2024-02-01'),
	 (112,'2024-02-02','4500055J','Maria dolores','Gimenez','Hidalgo','maria dolores.gimenez.hidalgo@gmail.com','660071718','47007','2000-11-25','47','3','Izq.','María Zambrano','3Izq.','So Won','Drama','Una niña llamada So Won se convierte en víctima de la violencia. Su familia pasa por la desesperación y el dolor al intentar abrir otra puerta en su vida.','Lee Joon-ik','2024-02-02',NULL),
	 (47,'2024-02-02','2285124M','Jose ignacio','Rojas','Blanco','jose ignacio.rojas.blanco@gmail.com','604696806','47007','2010-11-06','57','4','A','Concepción Arenal','4A','El bueno, el feo y el malo','Western','Durante la Guerra de Secesión, tres cazadores de recompensas se lanzan a la búsqueda de un tesoro que ninguno de los tres truhanes puede localizar sin la ayuda de los otros dos. Tuco sabe que el tesoro se encuentra en un cementerio, mientras que Joe conoce el nombre inscrito en la tumba que lo esconde. Mientras tanto, Sentenza no duda en matar a mujeres y niños para conseguir su meta. De esta forma, los tres hombres colaboran en apariencia, pero al final intentarán eliminarse mutuamente.','Sergio Leone','2024-02-02',NULL),
	 (48,'2024-01-14','6098616M','Javier','Dominguez','Lozano','javier.dominguez.lozano@gmail.com','616805343','47008','2010-11-03','42','2','Der.','María Zambrano','2Der.','Uno de los nuestros','Drama','Henry, un niño de trece años de Brooklyn, vive fascinado con el mundo de los gángsters. Su sueño se hace realidad cuando entra a formar parte de la familia Pauline, dueña absoluta de la zona, que lo educan como un miembro más de la banda convirtiéndole en un destacado mafioso.','Martin Scorsese','2024-01-14','2024-01-15'),
	 (48,'2024-01-29','1124603H','Ivan','Santana','Medina','ivan.santana.medina@gmail.com','694804631','47007','2005-02-15','6','3','D','Francisco Pizarro','3D','Uno de los nuestros','Drama','Henry, un niño de trece años de Brooklyn, vive fascinado con el mundo de los gángsters. Su sueño se hace realidad cuando entra a formar parte de la familia Pauline, dueña absoluta de la zona, que lo educan como un miembro más de la banda convirtiéndole en un destacado mafioso.','Martin Scorsese','2024-01-29',NULL),
	 (49,'2024-02-02','1124603H','Ivan','Santana','Medina','ivan.santana.medina@gmail.com','694804631','47007','2005-02-15','6','3','D','Francisco Pizarro','3D','Uno de los nuestros','Drama','Henry, un niño de trece años de Brooklyn, vive fascinado con el mundo de los gángsters. Su sueño se hace realidad cuando entra a formar parte de la familia Pauline, dueña absoluta de la zona, que lo educan como un miembro más de la banda convirtiéndole en un destacado mafioso.','Martin Scorsese','2024-02-02',NULL),
	 (50,'2024-01-22','3913881V','Maria pilar','Gallego','Moya','maria pilar.gallego.moya@gmail.com','611154361','47003','2015-03-22','86','3','B','Iglesia','3B','Uno de los nuestros','Drama','Henry, un niño de trece años de Brooklyn, vive fascinado con el mundo de los gángsters. Su sueño se hace realidad cuando entra a formar parte de la familia Pauline, dueña absoluta de la zona, que lo educan como un miembro más de la banda convirtiéndole en un destacado mafioso.','Martin Scorsese','2024-01-22',NULL),
	 (51,'2024-01-19','6152776T','Margarita','Nuñez','Fuentes','margarita.nuñez.fuentes@gmail.com','614215413','47007','1998-03-02','62','2','Izq.','Bartolomé Esteban Murillo','2Izq.','Los siete samuráis','Acción','Una banda de forajidos atemorizan a los habitantes de un pequeño pueblo, saqueándolos periódicamente sin piedad. Para repeler estos ataques, los aldeanos deciden contratar a mercenarios. Finalmente, consiguen los servicios de 7 guerreros, 7 samurais dispuestos a defenderlos a cambio, tan solo, de cobijo y comida.','Akira Kurosawa','2024-01-19','2024-01-20'),
	 (51,'2024-01-23','7154832S','Andres','Moreno','Vega','andres.moreno.vega@gmail.com','650174329','47009','2003-01-01','11','2','Izq.','Real','2Izq.','Los siete samuráis','Acción','Una banda de forajidos atemorizan a los habitantes de un pequeño pueblo, saqueándolos periódicamente sin piedad. Para repeler estos ataques, los aldeanos deciden contratar a mercenarios. Finalmente, consiguen los servicios de 7 guerreros, 7 samurais dispuestos a defenderlos a cambio, tan solo, de cobijo y comida.','Akira Kurosawa','2024-01-23','2024-01-24'),
	 (51,'2024-01-27','4435315H','Lidia','Rubio','Benitez','lidia.rubio.benitez@gmail.com','621419327','47003','1993-09-12','91','2','Der.','Concepción Arenal','2Der.','Los siete samuráis','Acción','Una banda de forajidos atemorizan a los habitantes de un pequeño pueblo, saqueándolos periódicamente sin piedad. Para repeler estos ataques, los aldeanos deciden contratar a mercenarios. Finalmente, consiguen los servicios de 7 guerreros, 7 samurais dispuestos a defenderlos a cambio, tan solo, de cobijo y comida.','Akira Kurosawa','2024-01-27',NULL),
	 (52,'2024-01-19','2537526M','Jose antonio','Guerrero','Molina','jose antonio.guerrero.molina@gmail.com','675872614','47007','1991-11-30','17','3','Izq.','Dulcinea','3Izq.','Los siete samuráis','Acción','Una banda de forajidos atemorizan a los habitantes de un pequeño pueblo, saqueándolos periódicamente sin piedad. Para repeler estos ataques, los aldeanos deciden contratar a mercenarios. Finalmente, consiguen los servicios de 7 guerreros, 7 samurais dispuestos a defenderlos a cambio, tan solo, de cobijo y comida.','Akira Kurosawa','2024-01-19','2024-01-20'),
	 (52,'2024-01-27','4437589S','Pedro','Iglesias','Garrido','pedro.iglesias.garrido@gmail.com','634143203','47000','1999-12-02','34','1','B','Federico García Lorca','1B','Los siete samuráis','Acción','Una banda de forajidos atemorizan a los habitantes de un pequeño pueblo, saqueándolos periódicamente sin piedad. Para repeler estos ataques, los aldeanos deciden contratar a mercenarios. Finalmente, consiguen los servicios de 7 guerreros, 7 samurais dispuestos a defenderlos a cambio, tan solo, de cobijo y comida.','Akira Kurosawa','2024-01-27',NULL),
	 (53,'2024-01-25','7402615L','Eva','Hidalgo','Cortes','eva.hidalgo.cortes@gmail.com','666238181','47003','2010-09-02','57','2','A','Fuente','2A','Los siete samuráis','Acción','Una banda de forajidos atemorizan a los habitantes de un pequeño pueblo, saqueándolos periódicamente sin piedad. Para repeler estos ataques, los aldeanos deciden contratar a mercenarios. Finalmente, consiguen los servicios de 7 guerreros, 7 samurais dispuestos a defenderlos a cambio, tan solo, de cobijo y comida.','Akira Kurosawa','2024-01-25',NULL),
	 (54,'2024-01-31','7154832S','Andres','Moreno','Vega','andres.moreno.vega@gmail.com','650174329','47009','2003-01-01','11','2','Izq.','Real','2Izq.','Los siete samuráis','Acción','Una banda de forajidos atemorizan a los habitantes de un pequeño pueblo, saqueándolos periódicamente sin piedad. Para repeler estos ataques, los aldeanos deciden contratar a mercenarios. Finalmente, consiguen los servicios de 7 guerreros, 7 samurais dispuestos a defenderlos a cambio, tan solo, de cobijo y comida.','Akira Kurosawa','2024-01-31','2024-02-01'),
	 (54,'2024-02-02','6298662C','Angela','Lopez','Rubio','angela.lopez.rubio@gmail.com','628535856','47001','1992-06-26','37','3','Der.','Real','3Der.','Los siete samuráis','Acción','Una banda de forajidos atemorizan a los habitantes de un pequeño pueblo, saqueándolos periódicamente sin piedad. Para repeler estos ataques, los aldeanos deciden contratar a mercenarios. Finalmente, consiguen los servicios de 7 guerreros, 7 samurais dispuestos a defenderlos a cambio, tan solo, de cobijo y comida.','Akira Kurosawa','2024-02-02',NULL),
	 (74,'2024-01-18','3252617A','Pilar','Marquez','Lozano','pilar.marquez.lozano@gmail.com','621541699','47000','2000-07-13','95','1','B','Eras','1B','Gabriel''s Inferno','Romántica','El enigmático y atractivo profesor Gabriel Emerson, reconocido especialista en Dante, es un hombre torturado por su pasado y orgulloso del prestigio que ha conseguido, aunque también es consciente de que es un imán para el pecado y, en especial, para la lujuria.','Tosca Musk','2024-01-18',NULL),
	 (55,'2024-01-14','8958239S','Juana','Peña','Sanz','juana.peña.sanz@gmail.com','618221724','47006','2001-07-12','28','2','Der.','Agustina de Aragón','2Der.','La tumba de las luciérnagas','Animación','Verano de 1945. La aviación estadounidense somete las ciudades japonesas a continuos ataques aéreos. En uno de ellos, una incursión con bombas incendiarias convierte la ciudad de Kōbe en un infierno humeante, para los dos protagonistas (Seita, de 14 años, y su hermanita Setsuko, de 5). El joven Seita y su pequeña hermana Setsuko son hijos de un oficial de la marina japonesa. Durante la Segunda Guerra Mundial, ambos viven con su madre, pero un día, tras un bombardeo, ellos se retrasan y no consiguen llegar al búnker donde ella los espera.','Isao Takahata','2024-01-14',NULL),
	 (56,'2024-01-14','6693383S','Rodrigo','Mendez','Cruz','rodrigo.mendez.cruz@gmail.com','674794168','47008','2015-01-26','10','2','A','Reina Sofía','2A','La tumba de las luciérnagas','Animación','Verano de 1945. La aviación estadounidense somete las ciudades japonesas a continuos ataques aéreos. En uno de ellos, una incursión con bombas incendiarias convierte la ciudad de Kōbe en un infierno humeante, para los dos protagonistas (Seita, de 14 años, y su hermanita Setsuko, de 5). El joven Seita y su pequeña hermana Setsuko son hijos de un oficial de la marina japonesa. Durante la Segunda Guerra Mundial, ambos viven con su madre, pero un día, tras un bombardeo, ellos se retrasan y no consiguen llegar al búnker donde ella los espera.','Isao Takahata','2024-01-14','2024-01-15'),
	 (56,'2024-01-29','7281621M','Jorge','Mendez','Alvarez','jorge.mendez.alvarez@gmail.com','615944300','47006','2002-05-26','56','3','Izq.','Sol','3Izq.','La tumba de las luciérnagas','Animación','Verano de 1945. La aviación estadounidense somete las ciudades japonesas a continuos ataques aéreos. En uno de ellos, una incursión con bombas incendiarias convierte la ciudad de Kōbe en un infierno humeante, para los dos protagonistas (Seita, de 14 años, y su hermanita Setsuko, de 5). El joven Seita y su pequeña hermana Setsuko son hijos de un oficial de la marina japonesa. Durante la Segunda Guerra Mundial, ambos viven con su madre, pero un día, tras un bombardeo, ellos se retrasan y no consiguen llegar al búnker donde ella los espera.','Isao Takahata','2024-01-29',NULL),
	 (57,'2024-01-08','6101425P','Maria isabel','Saez','Castro','maria isabel.saez.castro@gmail.com','669188648','47006','1997-08-03','45','1','B','Nueva','1B','La vida es bella','Comedia','En 1939, a punto de estallar la Segunda Guerra Mundial (1939-1945), el extravagante Guido llega a Arezzo, en la Toscana, con la intención de abrir una librería. Allí conoce a la encantadora Dora y, a pesar de que es la prometida del fascista Rodolfo, se casa con ella y tiene un hijo. Al estallar la guerra, los tres son internados en un campo de exterminio, donde Guido hará lo imposible para hacer creer a su hijo que la terrible situación que están padeciendo es tan sólo un juego.','Roberto Benigni','2024-01-08',NULL),
	 (58,'2024-01-15','6098616M','Javier','Dominguez','Lozano','javier.dominguez.lozano@gmail.com','616805343','47008','2010-11-03','42','2','Der.','María Zambrano','2Der.','La vida es bella','Comedia','En 1939, a punto de estallar la Segunda Guerra Mundial (1939-1945), el extravagante Guido llega a Arezzo, en la Toscana, con la intención de abrir una librería. Allí conoce a la encantadora Dora y, a pesar de que es la prometida del fascista Rodolfo, se casa con ella y tiene un hijo. Al estallar la guerra, los tres son internados en un campo de exterminio, donde Guido hará lo imposible para hacer creer a su hijo que la terrible situación que están padeciendo es tan sólo un juego.','Roberto Benigni','2024-01-15','2024-01-16'),
	 (58,'2024-01-27','7402615L','Eva','Hidalgo','Cortes','eva.hidalgo.cortes@gmail.com','666238181','47003','2010-09-02','57','2','A','Fuente','2A','La vida es bella','Comedia','En 1939, a punto de estallar la Segunda Guerra Mundial (1939-1945), el extravagante Guido llega a Arezzo, en la Toscana, con la intención de abrir una librería. Allí conoce a la encantadora Dora y, a pesar de que es la prometida del fascista Rodolfo, se casa con ella y tiene un hijo. Al estallar la guerra, los tres son internados en un campo de exterminio, donde Guido hará lo imposible para hacer creer a su hijo que la terrible situación que están padeciendo es tan sólo un juego.','Roberto Benigni','2024-01-27',NULL),
	 (59,'2024-01-21','6152776T','Margarita','Nuñez','Fuentes','margarita.nuñez.fuentes@gmail.com','614215413','47007','1998-03-02','62','2','Izq.','Bartolomé Esteban Murillo','2Izq.','Cinema Paradiso','Drama','En un pequeño pueblo siciliano durante los años previos a la llegada de la televisión (justo al finalizar la Segunda Guerra Mundial) el joven Toto vivía fascinado por el cine. Toto trata de entablar amistad con Alfredo, el proyeccionista del cine local, una persona muy irritable pero con un gran corazón. Todos estos hechos se presentan en forma de nostálgicos recuerdos de Toto que ha crecido hasta convertirse en un cineasta de éxito, y que revive a su infancia cuando recibe la noticia de que Alfredo ha muerto.','Giuseppe Tornatore','2024-01-21',NULL),
	 (60,'2024-01-30','6590576H','Jaime','Morales','Soler','jaime.morales.soler@gmail.com','699944454','47001','2002-06-20','38','3','Der.','Sol','3Der.','Cinema Paradiso','Drama','En un pequeño pueblo siciliano durante los años previos a la llegada de la televisión (justo al finalizar la Segunda Guerra Mundial) el joven Toto vivía fascinado por el cine. Toto trata de entablar amistad con Alfredo, el proyeccionista del cine local, una persona muy irritable pero con un gran corazón. Todos estos hechos se presentan en forma de nostálgicos recuerdos de Toto que ha crecido hasta convertirse en un cineasta de éxito, y que revive a su infancia cuando recibe la noticia de que Alfredo ha muerto.','Giuseppe Tornatore','2024-01-30',NULL),
	 (61,'2024-01-07','1124603H','Ivan','Santana','Medina','ivan.santana.medina@gmail.com','694804631','47007','2005-02-15','6','3','D','Francisco Pizarro','3D','Cinema Paradiso','Drama','En un pequeño pueblo siciliano durante los años previos a la llegada de la televisión (justo al finalizar la Segunda Guerra Mundial) el joven Toto vivía fascinado por el cine. Toto trata de entablar amistad con Alfredo, el proyeccionista del cine local, una persona muy irritable pero con un gran corazón. Todos estos hechos se presentan en forma de nostálgicos recuerdos de Toto que ha crecido hasta convertirse en un cineasta de éxito, y que revive a su infancia cuando recibe la noticia de que Alfredo ha muerto.','Giuseppe Tornatore','2024-01-07','2024-01-08'),
	 (61,'2024-01-28','2237186E','Eduardo','Alonso','Castro','eduardo.alonso.castro@gmail.com','684839436','47007','1999-07-25','12','1','D','Reina Sofía','1D','Cinema Paradiso','Drama','En un pequeño pueblo siciliano durante los años previos a la llegada de la televisión (justo al finalizar la Segunda Guerra Mundial) el joven Toto vivía fascinado por el cine. Toto trata de entablar amistad con Alfredo, el proyeccionista del cine local, una persona muy irritable pero con un gran corazón. Todos estos hechos se presentan en forma de nostálgicos recuerdos de Toto que ha crecido hasta convertirse en un cineasta de éxito, y que revive a su infancia cuando recibe la noticia de que Alfredo ha muerto.','Giuseppe Tornatore','2024-01-28',NULL),
	 (62,'2024-01-24','6298662C','Angela','Lopez','Rubio','angela.lopez.rubio@gmail.com','628535856','47001','1992-06-26','37','3','Der.','Real','3Der.','Taylor Swift: Gira de estadios Reputation','Musical','Taylor Swift se sube al escenario en Dallas durante su Reputation Stadium Tour y festeja una gran noche de música, recuerdos y magia visual.','Paul Dugdale','2024-01-24','2024-01-25');

alter table telefono 
add constraint fk_socio_telefono 
foreign key (id_socio) references socio(id);

alter table direccion 
add constraint fk_socio_direccion 
foreign key (id) references socio(id);

alter table pelicula 
add constraint fk_genero_pelicula 
foreign key (id_genero) references genero(id);

alter table pelicula 
add constraint fk_director_pelicula 
foreign key (id_director) references director(id);

alter table copia 
add constraint fk_pelicula_copia 
foreign key (id_pelicula) references pelicula(id);

alter table prestamo 
add constraint fk_socio_prestamo 
foreign key (id_socio) references socio(id);

alter table prestamo 
add constraint fk_copia_prestamo 
foreign key (id_copia) references copia(id);

-- Creación de chequeos para asegurar que no tengo valores duplicados
alter table pelicula add constraint unique_pelicula_genero_director unique (titulo, id_director, id_genero);
alter table socio  add constraint unique_identificacion unique (identificacion);
alter table director add constraint unique_nombre_director unique (nombre);
alter table genero add constraint unique_valor_genero unique (valor);

insert into genero(valor)
select distinct genero from tmp_videoclub tv;

insert into director(nombre)
select distinct director from tmp_videoclub tv;

insert into socio(identificacion, nombre, apellido, fecha_nacimiento)
select distinct tv.dni, tv.nombre, concat(tv.apellido_1, ' ', tv.apellido_2), cast(tv.fecha_nacimiento as date) from tmp_videoclub tv;

insert into direccion (id, calle, numero, piso, cp)
select distinct s.id , tv.calle, tv.numero, concat(tv.piso, ' ', tv.letra), cast(tv.codigo_postal as integer) from tmp_videoclub tv
inner join socio s on s.identificacion = tv.dni;

insert into pelicula (titulo, id_genero, id_director, sinopsis)
select distinct tv.titulo, g.id, d.id, tv.sinopsis from tmp_videoclub tv 
inner join genero g on g.valor = tv.genero
inner join director d on d.nombre = tv.director;

insert into copia (valor, id_pelicula)
select distinct tv.id_copia, p.id from tmp_videoclub tv
inner join pelicula p on p.titulo = tv.titulo;

insert into prestamo (id_socio, id_copia, fecha_retiro, fecha_devolucion)
select s.id, c.id, tv.fecha_alquiler , tv.fecha_devolucion from tmp_videoclub tv
inner join socio s on s.identificacion = tv.dni
inner join copia c on c.valor = tv.id_copia ;

-- Eliminación de tabla temporal
drop table tmp_videoclub;


--Qué socio alquiló qué copia?
select p2.id_socio, p2.id_copia, p.titulo from pelicula p
inner join copia c on p.id = c.id_pelicula 
inner join prestamo p2 on c.id = p2.id_copia 
group by p2.id_socio, p2.id_copia, p.titulo;

insert into pelicula (titulo, id_genero, id_director, sinopsis) values
	('El secreto de sus ojos', '1', '1', 'Peli prueba');

insert into copia (valor, id_pelicula) values
	('100', '24');

--Qué peliculas hay disponibles y cuántas copias de cada una?
select p.titulo as titulos_disponibles, count(c.valor) as cantidad_copias from pelicula p 
inner join copia c  on p.id = c.id_pelicula
left join prestamo p2 on c.id = p2.id_copia and p2.fecha_retiro is not null and p2.fecha_devolucion is null
where p2.id is null
group by p.titulo;